<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>scopeName</key>
        <string>testOutput.log</string>
        <key>fileTypes</key>
        <array>
            <string>log</string>
        </array>
        <key>name</key>
        <string>Log file</string>
        <key>patterns</key>
        <array>
            <!-- py.test file summary -->
            <!--
            tests/test_another.py ..
            tests/test_multi.py ....F.....F
            tests/test_one.py F.
            tests/test_three.py ...F
            -->
            <dict>
                <key>match</key>
                <string>.*\.py \.*F(F|\.){0,}$</string>
                <key>name</key>
                <string>error-token</string>
            </dict>
            <dict>
                <key>match</key>
                <string>.*\.py (s|F|\.){0,}s(s|F|\.){0,}$</string>
                <key>name</key>
                <string>warn-token</string>
            </dict>
            <!-- py.test errors -->
            <!--
            >       assert False
            E       assert False
            -->
            <dict>
                <key>match</key>
                <string>^E    .*</string>
                <key>name</key>
                <string>error-token</string>
            </dict>
            <!-- py.test errors -->
            <!--
            _________ Test_CheckMyApp.Test_NestedClassA.test_nested_class_methodC __________

            self = <test_multi.Test_NestedClassA instance at 0x107deabd8>

                def test_nested_class_methodC(self):
            >       assert False
            E       assert False

            tests/test_multi.py:19: AssertionError
            -->
            <dict>
                <key>match</key>
                <string>.*\.py:[0-9]+: ([a-z]|[A-Z])*Error$</string>
                <key>name</key>
                <string>error-token</string>
            </dict>
            <!-- py.test errors -->
            <dict>
                <key>match</key>
                <string> ([a-z]|[A-Z])*Error:</string>
                <key>name</key>
                <string>error-token</string>
            </dict>
            <!-- unittest error -->
            <!-- 
            test_A (test_one.Test_test1) ... FAIL
            Traceback (most recent call last):
            File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 331, in run
                testMethod()
            File "/Users/donjayamanne/Desktop/Development/Python/Temp/MyEnvs/tests/test_one.py", line 8, in test_A
                self.fail("Not implemented")
            File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 412, in fail
                raise self.failureException(msg)
            AssertionError: Not implemented
            -->
            <dict>
                <key>match</key>
                <string>\.\.\. FAIL$</string>
                <key>name</key>
                <string>error-token</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\.\.\. skipped '.*'$</string>
                <key>name</key>
                <string>warn-token</string>
            </dict>
            <!-- unittest error -->
            <!-- 
            ======================================================================
            FAIL: test_A (test_one.Test_test1)
            ----------------------------------------------------------------------
            Traceback (most recent call last):
            File "/Users/donjayamanne/Desktop/Development/Python/Temp/MyEnvs/tests/test_one.py", line 8, in test_A
                self.fail("Not implemented")
            AssertionError: Not implemented
            -->
            <dict>
                <key>match</key>
                <string>^FAIL: .*\)$</string>
                <key>name</key>
                <string>error-token</string>
            </dict>
            <dict>
                <key>match</key>
                <string>^ERROR: .*</string>
                <key>name</key>
                <string>error-token</string>
            </dict>
            <dict>
                <key>match</key>
                <string>^([a-z]|[A-Z])*Error: .*</string>
                <key>name</key>
                <string>error-token</string>
            </dict>
            <!-- py.test summary -->
            <!-- 
            ================ 8 failed, 28 passed, 2 skipped in 0.11 seconds ================
            -->
            <dict>
                <key>match</key>
                <string>^=+.* failed.*=$</string>
                <key>name</key>
                <string>error-token</string>
            </dict>
            <dict>
                <key>match</key>
                <string>^=+.* skipped.*=$</string>
                <key>name</key>
                <string>warn-token</string>
            </dict>
            <dict>
                <key>match</key>
                <string>^=+.* passed.*=$</string>
                <key>name</key>
                <string>comment.line</string>
            </dict>
            <dict>
                <key>match</key>
                <string>collected [0-9]+ items</string>
                <key>name</key>
                <string>info-token</string>
            </dict>
            <!-- py.test summary -->
            <!-- 
            ----------------------------------------------------------------------
            Ran 10 tests in 0.005s

            FAILED (failures=4, skipped=2)
            -->
            <dict>
                <key>match</key>
                <string>^RAN [0-9]+ test(s){0,1} in [0-9]+\.[0-9]+s$</string>
                <key>name</key>
                <string>info-token</string>
            </dict>
            <dict>
                <key>match</key>
                <string>^FAILED \(.*\)$</string>
                <key>name</key>
                <string>error-token</string>
            </dict>
            <dict>
                <key>match</key>
                <string>^OK$</string>
                <key>name</key>
                <string>comment.line</string>
            </dict>
            <dict>
                <key>match</key>
                <string>^OK \(skipped=[0-9]+\)$</string>
                <key>name</key>
                <string>comment.line</string>
            </dict>
        </array>
        <key>uuid</key>
        <string>ab259404-3072-4cd4-a943-7cbbd32e373f</string>
    </dict>
</plist>