name: 'Build VSIX'
description: "Build the extension's VSIX"

outputs:
  path:
    description: 'Path to the VSIX'
    value: 'ms-python-insiders.vsix'

runs:
  using: 'composite'
  steps:
    # # For faster/better builds of sdists.
    # - run: python -m pip install wheel
    #   shell: bash

    # - run: python -m pip --disable-pip-version-check install -t ./pythonFiles/lib/python --no-cache-dir --implementation py --no-deps --upgrade -r requirements.txt
    #   shell: bash

    # - run: |
    #     python -m pip --disable-pip-version-check install -r build/debugger-install-requirements.txt
    #     python ./pythonFiles/install_debugpy.py
    #   shell: bash

    - run: npm ci --prefer-offline
      shell: bash

    # Use the GITHUB_RUN_ID environment variable to update the build number.
    # GITHUB_RUN_ID is a unique number for each run within a repository.
    # This number does not change if you re-run the workflow run.
    - run: npm run updateBuildNumber -- --buildNumber $GITHUB_RUN_ID
      shell: bash

    - run: npm run package
      shell: bash
