name: 'Lock Issues'

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  issues: write

concurrency:
  group: lock

jobs:
  lock-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v3
        with:
          repository: 'microsoft/vscode-github-triage-actions'
          ref: stable
          path: ./actions

      - name: Install Actions
        run: npm install --production --prefix ./actions

      - name: 'Lock Issues'
        uses: ./actions/python-lock-issues
        with:
          token: ${{ github.token }}
