name: PR files
on:
  pull_request:
    types:
      # On by default if you specify no types.
      - 'opened'
      - 'reopened'
      - 'synchronize'
      # For `skip-label` only.
      - 'labeled'
      - 'unlabeled'

jobs:
  changed-files-in-pr:
    name: 'Check for changed files'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v3
        with:
          repository: 'microsoft/vscode-github-triage-actions'
          ref: stable
          path: ./actions

      - name: Install Actions
        run: npm install --production --prefix ./actions

      - name: Check for changed files
        uses: ./actions/python-pr-file-check
