name: 'PR labels'
on:
  pull_request:
    types:
      - 'opened'
      - 'reopened'
      - 'labeled'
      - 'unlabeled'
      - 'synchronize'

jobs:
  classify:
    name: 'Classify PR'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v3
        with:
          repository: 'microsoft/vscode-github-triage-actions'
          ref: stable
          path: ./actions

      - name: Install Actions
        run: npm install --production --prefix ./actions

      - name: Classify PR
        uses: ./actions/python-pr-labels
